name: Test Self-Hosted Runner

on:
  push:
    branches: [ main, master ]  # Triggers on both branches
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Manual trigger button

jobs:
  test:
    runs-on: self-hosted  # Uses your self-hosted runner
    
    env:
      ACTIONS_STEP_DEBUG: true  # Enable debug logging

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Environment Test
      run: |
        echo "Self-hosted runner is working!"
        echo "Branch: ${{ github.ref_name }}"
        echo "Repository: ${{ github.repository }}"
        echo "OS: $env:OS"
        echo "Computer: $env:COMPUTERNAME"
        echo "PowerShell Version: $($PSVersionTable.PSVersion)"
        Get-Date
        
    - name: List Repository Contents
      run: |
        echo "Repository Contents:"
        Get-ChildItem -Force | Format-Table Name, Length, LastWriteTime
        
    - name: System Information
      run: |
        echo "System Info:"
        Get-ComputerInfo | Select-Object WindowsProductName, WindowsVersion, TotalPhysicalMemory
        
    - name: Check .NET Installation
      run: |
        echo ".NET Information:"
        try {
          dotnet --version
          dotnet --list-sdks
          dotnet --list-runtimes
        } catch {
          echo ".NET not installed or not in PATH"
        }
